#server
server:
  port: 8081

#my-sql
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/users
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  hibernate:
    ddl-auto: update
jwt:
  secret: "this-is-a-very-secret-key-at-least-32-chars"
  expiration: 3600000