#server
server:
  port: 8082

#my-sql
spring:
  application:
    name: restaurant-service
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  hibernate:
    ddl-auto: update
